include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    directives_ordering: true
    discarded_futures: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    unawaited_futures: true
    use_build_context_synchronously: true
